# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'untitled.ui'
##
## Created by: Qt User Interface Compiler version 6.5.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCommandLinkButton, QLabel, QLineEdit,
    QMainWindow, QMenuBar, QPushButton, QSizePolicy,
    QStatusBar, QWidget)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(819, 377)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(30, 200, 71, 21))
        font = QFont()
        font.setFamilies([u"Segoe UI"])
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(30, 130, 151, 31))
        font1 = QFont()
        font1.setFamilies([u"Segoe UI Black"])
        font1.setPointSize(12)
        font1.setBold(True)
        self.label_6.setFont(font1)
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(280, 50, 171, 20))
        font2 = QFont()
        font2.setPointSize(12)
        self.label_9.setFont(font2)
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(30, 10, 151, 31))
        self.label.setFont(font1)
        self.okta_login = QLineEdit(self.centralwidget)
        self.okta_login.setObjectName(u"okta_login")
        self.okta_login.setGeometry(QRect(110, 50, 113, 20))
        self.week_addr = QLineEdit(self.centralwidget)
        self.week_addr.setObjectName(u"week_addr")
        self.week_addr.setGeometry(QRect(460, 20, 251, 20))
        self.week_addr.setReadOnly(True)
        self.commandLinkButton = QCommandLinkButton(self.centralwidget)
        self.commandLinkButton.setObjectName(u"commandLinkButton")
        self.commandLinkButton.setGeometry(QRect(450, 200, 161, 41))
        self.btn_week = QPushButton(self.centralwidget)
        self.btn_week.setObjectName(u"btn_week")
        self.btn_week.setGeometry(QRect(730, 20, 75, 23))
        self.otrs_pass = QLineEdit(self.centralwidget)
        self.otrs_pass.setObjectName(u"otrs_pass")
        self.otrs_pass.setGeometry(QRect(110, 200, 113, 20))
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(280, 20, 121, 20))
        self.label_8.setFont(font2)
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(30, 50, 51, 21))
        self.label_3.setFont(font)
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(30, 160, 51, 21))
        self.label_7.setFont(font)
        self.okta_pass = QLineEdit(self.centralwidget)
        self.okta_pass.setObjectName(u"okta_pass")
        self.okta_pass.setGeometry(QRect(110, 90, 113, 20))
        self.email_file = QLineEdit(self.centralwidget)
        self.email_file.setObjectName(u"email_file")
        self.email_file.setGeometry(QRect(460, 50, 251, 20))
        self.email_file.setReadOnly(True)
        self.otrs_login = QLineEdit(self.centralwidget)
        self.otrs_login.setObjectName(u"otrs_login")
        self.otrs_login.setGeometry(QRect(110, 160, 113, 20))
        self.label_10 = QLabel(self.centralwidget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(640, 310, 141, 16))
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(30, 90, 71, 21))
        self.label_4.setFont(font)
        self.btn_snd = QPushButton(self.centralwidget)
        self.btn_snd.setObjectName(u"btn_snd")
        self.btn_snd.setGeometry(QRect(730, 50, 75, 23))
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(280, 250, 161, 21))
        self.label_12 = QLabel(self.centralwidget)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(280, 80, 131, 20))
        self.label_12.setFont(font2)
        self.btn_prt_1151 = QPushButton(self.centralwidget)
        self.btn_prt_1151.setObjectName(u"btn_prt_1151")
        self.btn_prt_1151.setGeometry(QRect(724, 80, 81, 23))
        self.email_file_2 = QLineEdit(self.centralwidget)
        self.email_file_2.setObjectName(u"email_file_2")
        self.email_file_2.setGeometry(QRect(460, 80, 251, 20))
        self.email_file_2.setReadOnly(True)
        self.email_file_3 = QLineEdit(self.centralwidget)
        self.email_file_3.setObjectName(u"email_file_3")
        self.email_file_3.setGeometry(QRect(460, 110, 251, 20))
        self.email_file_3.setReadOnly(True)
        self.label_13 = QLabel(self.centralwidget)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(280, 110, 161, 20))
        self.label_13.setFont(font2)
        self.btn_dir = QPushButton(self.centralwidget)
        self.btn_dir.setObjectName(u"btn_dir")
        self.btn_dir.setGeometry(QRect(714, 110, 91, 23))
        self.pushButton_2 = QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(450, 250, 171, 51))
        self.email_file_4 = QLineEdit(self.centralwidget)
        self.email_file_4.setObjectName(u"email_file_4")
        self.email_file_4.setGeometry(QRect(460, 140, 251, 20))
        self.email_file_4.setReadOnly(True)
        self.btn_dir_2 = QPushButton(self.centralwidget)
        self.btn_dir_2.setObjectName(u"btn_dir_2")
        self.btn_dir_2.setGeometry(QRect(714, 140, 91, 23))
        self.label_14 = QLabel(self.centralwidget)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(280, 140, 161, 20))
        self.label_14.setFont(font2)
        self.pushButton_3 = QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(630, 190, 171, 51))
        self.okta_pass_2 = QLineEdit(self.centralwidget)
        self.okta_pass_2.setObjectName(u"okta_pass_2")
        self.okta_pass_2.setGeometry(QRect(460, 170, 113, 20))
        self.label_11 = QLabel(self.centralwidget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(280, 170, 141, 21))
        self.label_11.setFont(font)
        self.pushButton_4 = QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(630, 250, 171, 51))
        self.pushButton_5 = QPushButton(self.centralwidget)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(280, 280, 161, 21))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 819, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"LWIS TRACK RESPONSE", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Password", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"OTRS Login Details", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"LWIS file to send emails", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Okta Login Details", None))
        self.commandLinkButton.setText(QCoreApplication.translate("MainWindow", u"Send main emails", None))
        self.btn_week.setText(QCoreApplication.translate("MainWindow", u"Select file", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"LWIS week file", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Login", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Login", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Developed By SC Ukraine", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Password", None))
        self.btn_snd.setText(QCoreApplication.translate("MainWindow", u"Select file", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"Prepare Document 2 emails", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Partner 1151 file", None))
        self.btn_prt_1151.setText(QCoreApplication.translate("MainWindow", u"Select file", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Partner 1151 directory", None))
        self.btn_dir.setText(QCoreApplication.translate("MainWindow", u"Select directory", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"Send 1151 Relation emails", None))
        self.btn_dir_2.setText(QCoreApplication.translate("MainWindow", u"Select directory", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Partner main directory", None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"Create main tickets", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Owner name", None))
        self.pushButton_4.setText(QCoreApplication.translate("MainWindow", u"Create 1151 tickets", None))
        self.pushButton_5.setText(QCoreApplication.translate("MainWindow", u"Prepare Document 1 email", None))
    # retranslateUi

